name: 测试

on:
  push:
  workflow_dispatch:

jobs:
  build-n-deploy:
    runs-on: ubuntu-latest
    env:
      NUXT_APP_BASE_URL: /StrangeAttractors/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装 Bun
        uses: oven-sh/setup-bun@v1

      - name: 安装依赖
        run: bun install --frozen-lockfile

      - name: 构建网页
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: bun generate
